### ISSUE TITLE
SWMM/pyswmm 

### ISSUE THREAD

**Issue by bemcdonnell** [hydrohamed/hydroinformatics-roadmap#1]
@hydrohamed , Great concept here! I plan to share this with many of the young engineers entering this space. I thought I might use this opportunity to make a recommendation. Any hydroinformatics engineer who works in the stormwater space should definitely become familiar with more of a programming approach to using SWMM.  Therefore, I recommend adding pyswmm to your list

https://github.com/pyswmm/pyswmm

**Comment by samsamihd** [comment]
@bemcdonnell Thank you for the great suggestion and for your positive feedback on the roadmap. I'm glad to hear that you find it valuable enough to share with others in the field.

I completely agree that PySWMM is an essential tool for hydroinformatics engineers working in the stormwater niche. I will add it to the roadmap shortly. If you have any other recommendations or feedback, please feel free to share!
